fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5 # Or specific version
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy app/
        language: system
        types: [python]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: uv run pytest -x
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-push]
