"""Add ConceptDraft

Revision ID: 0bc00a00e753
Revises: e291e733cadd
Create Date: 2026-06-28 13:56:06.077802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0bc00a00e753"
down_revision: Union[str, Sequence[str], None] = "e291e733cadd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concept_drafts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=True),
        sa.Column("draft_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("idx_concepts_fts"), table_name="concepts", postgresql_using="gin")
    op.create_index(
        "idx_concepts_fts",
        "concepts",
        [sa.literal_column("to_tsvector('french', nom || ' ' || enonce)")],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_concepts_fts", table_name="concepts", postgresql_using="gin")
    op.create_index(
        op.f("idx_concepts_fts"),
        "concepts",
        [sa.literal_column("to_tsvector('french'::regconfig, (nom || ' '::text) || enonce)")],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_table("concept_drafts")
    # ### end Alembic commands ###
