"""Add vector embedding

Revision ID: 836ca5b34b89
Revises: 0bc00a00e753
Create Date: 2026-07-08 23:14:11.394869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "836ca5b34b89"
down_revision: Union[str, Sequence[str], None] = "0bc00a00e753"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("concepts", sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.drop_index("idx_concepts_fts", table_name="concepts", postgresql_using="gin")
    op.create_index(
        "idx_concepts_fts",
        "concepts",
        [sa.text("to_tsvector('french', nom || ' ' || enonce)")],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_concepts_fts", table_name="concepts", postgresql_using="gin")
    op.create_index(
        "idx_concepts_fts",
        "concepts",
        [sa.text("to_tsvector('french'::regconfig, (nom || ' '::text) || enonce)")],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_column("concepts", "embedding")
    # ### end Alembic commands ###
