"""migrate_user_id_to_uuid

Revision ID: a470e9c19f53
Revises: f79dc7489ad5
Create Date: 2026-06-27 19:13:55.789790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a470e9c19f53"
down_revision: Union[str, Sequence[str], None] = "f79dc7489ad5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Drop all foreign keys referencing users.id
    op.drop_constraint("comments_user_id_fkey", "comments", type_="foreignkey")
    op.drop_constraint("concept_versions_modified_by_fkey", "concept_versions", type_="foreignkey")
    op.drop_constraint("concept_views_user_id_fkey", "concept_views", type_="foreignkey")
    op.drop_constraint("password_reset_tokens_user_id_fkey", "password_reset_tokens", type_="foreignkey")
    op.drop_constraint("user_contributions_user_id_fkey", "user_contributions", type_="foreignkey")
    op.drop_constraint("user_favorites_user_id_fkey", "user_favorites", type_="foreignkey")
    op.drop_constraint("user_sessions_user_id_fkey", "user_sessions", type_="foreignkey")

    # Drop default on users.id
    op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")

    # 2. Alter columns to UUID
    op.alter_column(
        "users",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.Uuid(),
        existing_nullable=False,
        postgresql_using="md5(id::text)::uuid",
    )

    op.alter_column(
        "comments",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.Uuid(),
        nullable=True,
        postgresql_using="md5(user_id::text)::uuid",
    )

    op.alter_column(
        "concept_versions",
        "modified_by",
        existing_type=sa.INTEGER(),
        type_=sa.Uuid(),
        existing_nullable=True,
        postgresql_using="md5(modified_by::text)::uuid",
    )

    op.alter_column(
        "concept_views",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.Uuid(),
        existing_nullable=True,
        postgresql_using="md5(user_id::text)::uuid",
    )

    op.alter_column(
        "password_reset_tokens",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.Uuid(),
        existing_nullable=True,
        postgresql_using="md5(user_id::text)::uuid",
    )

    op.alter_column(
        "user_contributions",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.Uuid(),
        existing_nullable=True,
        postgresql_using="md5(user_id::text)::uuid",
    )

    op.alter_column(
        "user_favorites",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.Uuid(),
        existing_nullable=False,
        postgresql_using="md5(user_id::text)::uuid",
    )

    op.alter_column(
        "user_sessions",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.Uuid(),
        existing_nullable=True,
        postgresql_using="md5(user_id::text)::uuid",
    )

    # 3. Create indices and Recreate foreign keys
    op.create_foreign_key(None, "comments", "users", ["user_id"], ["id"], ondelete="SET NULL")

    op.drop_constraint("concept_tags_concept_id_fkey", "concept_tags", type_="foreignkey")
    op.create_foreign_key(None, "concept_tags", "concepts", ["concept_id"], ["id"], ondelete="CASCADE")

    op.create_index("idx_concept_versions_modified_by", "concept_versions", ["modified_by"], unique=False)
    op.create_foreign_key(None, "concept_versions", "users", ["modified_by"], ["id"], ondelete="SET NULL")

    op.create_index("idx_concept_views_concept_id", "concept_views", ["concept_id"], unique=False)
    op.create_index("idx_concept_views_user_id", "concept_views", ["user_id"], unique=False)
    op.create_foreign_key(None, "concept_views", "users", ["user_id"], ["id"], ondelete="SET NULL")

    op.create_index("idx_concepts_categorie_id", "concepts", ["categorie_id"], unique=False)
    op.create_index(
        "idx_concepts_fts",
        "concepts",
        [sa.text("to_tsvector('french', nom || ' ' || enonce)")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("idx_concepts_mathematicien_id", "concepts", ["mathematicien_id"], unique=False)
    op.create_index("idx_concepts_type_id", "concepts", ["type_id"], unique=False)

    op.create_index("idx_password_reset_tokens_user_id", "password_reset_tokens", ["user_id"], unique=False)
    op.create_foreign_key(None, "password_reset_tokens", "users", ["user_id"], ["id"], ondelete="CASCADE")

    op.create_index("idx_user_contributions_user_id", "user_contributions", ["user_id"], unique=False)
    op.create_foreign_key(None, "user_contributions", "users", ["user_id"], ["id"], ondelete="SET NULL")

    op.create_index("idx_user_favorites_user_id", "user_favorites", ["user_id"], unique=False)
    op.create_foreign_key(None, "user_favorites", "users", ["user_id"], ["id"], ondelete="CASCADE")

    op.create_index("idx_user_sessions_user_id", "user_sessions", ["user_id"], unique=False)
    op.create_foreign_key(None, "user_sessions", "users", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=sa.Uuid(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("nextval('users_id_seq'::regclass)"),
    )
    op.drop_constraint(None, "user_sessions", type_="foreignkey")
    op.create_foreign_key("user_sessions_user_id_fkey", "user_sessions", "users", ["user_id"], ["id"])
    op.drop_index("idx_user_sessions_user_id", table_name="user_sessions")
    op.alter_column("user_sessions", "user_id", existing_type=sa.Uuid(), type_=sa.INTEGER(), existing_nullable=True)
    op.drop_constraint(None, "user_favorites", type_="foreignkey")
    op.create_foreign_key("user_favorites_user_id_fkey", "user_favorites", "users", ["user_id"], ["id"])
    op.drop_index("idx_user_favorites_user_id", table_name="user_favorites")
    op.alter_column("user_favorites", "user_id", existing_type=sa.Uuid(), type_=sa.INTEGER(), existing_nullable=False)
    op.drop_constraint(None, "user_contributions", type_="foreignkey")
    op.create_foreign_key("user_contributions_user_id_fkey", "user_contributions", "users", ["user_id"], ["id"])
    op.drop_index("idx_user_contributions_user_id", table_name="user_contributions")
    op.alter_column(
        "user_contributions", "user_id", existing_type=sa.Uuid(), type_=sa.INTEGER(), existing_nullable=True
    )
    op.drop_constraint(None, "password_reset_tokens", type_="foreignkey")
    op.create_foreign_key("password_reset_tokens_user_id_fkey", "password_reset_tokens", "users", ["user_id"], ["id"])
    op.drop_index("idx_password_reset_tokens_user_id", table_name="password_reset_tokens")
    op.alter_column(
        "password_reset_tokens", "user_id", existing_type=sa.Uuid(), type_=sa.INTEGER(), existing_nullable=True
    )
    op.drop_index("idx_concepts_type_id", table_name="concepts")
    op.drop_index("idx_concepts_mathematicien_id", table_name="concepts")
    op.drop_index("idx_concepts_fts", table_name="concepts", postgresql_using="gin")
    op.drop_index("idx_concepts_categorie_id", table_name="concepts")
    op.drop_constraint(None, "concept_views", type_="foreignkey")
    op.create_foreign_key("concept_views_user_id_fkey", "concept_views", "users", ["user_id"], ["id"])
    op.drop_index("idx_concept_views_user_id", table_name="concept_views")
    op.drop_index("idx_concept_views_concept_id", table_name="concept_views")
    op.alter_column("concept_views", "user_id", existing_type=sa.Uuid(), type_=sa.INTEGER(), existing_nullable=True)
    op.drop_constraint(None, "concept_versions", type_="foreignkey")
    op.create_foreign_key("concept_versions_modified_by_fkey", "concept_versions", "users", ["modified_by"], ["id"])
    op.drop_index("idx_concept_versions_modified_by", table_name="concept_versions")
    op.alter_column(
        "concept_versions", "modified_by", existing_type=sa.Uuid(), type_=sa.INTEGER(), existing_nullable=True
    )
    op.drop_constraint(None, "concept_tags", type_="foreignkey")
    op.create_foreign_key("concept_tags_concept_id_fkey", "concept_tags", "concepts", ["concept_id"], ["id"])
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key("comments_user_id_fkey", "comments", "users", ["user_id"], ["id"])
    op.alter_column("comments", "user_id", existing_type=sa.Uuid(), type_=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
