"""add notifications

Revision ID: e291e733cadd
Revises: a470e9c19f53
Create Date: 2026-06-28 13:38:17.465146

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e291e733cadd"
down_revision: Union[str, Sequence[str], None] = "a470e9c19f53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_notifications_user_id_is_read", "notifications", ["user_id", "is_read"], unique=False)
    op.drop_index(op.f("idx_concepts_fts"), table_name="concepts", postgresql_using="gin")
    op.create_index(
        "idx_concepts_fts",
        "concepts",
        [sa.literal_column("to_tsvector('french', nom || ' ' || enonce)")],
        unique=False,
        postgresql_using="gin",
    )
    op.add_column("user_favorites", sa.Column("notify_on_change", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_favorites", "notify_on_change")
    op.drop_index("idx_concepts_fts", table_name="concepts", postgresql_using="gin")
    op.create_index(
        op.f("idx_concepts_fts"),
        "concepts",
        [sa.literal_column("to_tsvector('french'::regconfig, (nom || ' '::text) || enonce)")],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_index("idx_notifications_user_id_is_read", table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
